### ISSUE TITLE
Problems encountered during the use of pva plug-in 

### ISSUE THREAD

**Issue by linus-qintian** [mdavidsaver/cashark#12]
Hello, I am using cashark to analyze the EPICS network, and I encountered a problem.I use ca.lua and pva.lua in the same way. Wireshark has no problem when using the ca plug-in, but it will report an error when using the pva plug-in. According to the error message, how can I specify the TCP and UDP ports when I start wireshark with pva.lua? 
![Snipaste_2021-12-27_19-27-12](https://user-images.githubusercontent.com/65064941/147467560-fe8f1f7b-1de9-44d2-997e-52b7561ca13d.png)
Thanks for your help!

**Comment by mdavidsaver** [comment]
Which version of wireshark are you running?

https://github.com/mdavidsaver/cashark/blob/6448936200e7bf47a7da29138933e205ae567c64/pva.lua#L330-L334

I've seen registration succeed with wireshark >= 2.6

> ... how can I specify the TCP and UDP ports when I start wireshark with pva.lua?

See [11.4.2. User Specified Decodes](https://www.wireshark.org/docs/wsug_html_chunked/ChCustProtocolDissectionSection.html)

**Comment by linus-qintian** [comment]
The problem has been solved as you suggested. Thank you for your help!
