### ISSUE TITLE
PVA dissector fails to load using Wireshark 1.10.14

### ISSUE THREAD

**Issue by ralphlange** [mdavidsaver/cashark#3]
Lua: Error during loading:
 [string "/usr/lib64/wireshark/plugins/1.10.14/pva.lua"]:316: A protocol doesn't have a `register_heuristic' attribute

**Comment by mdavidsaver** [comment]
The wireshark Lua API has been gradually expanded, and the heuristic dissectors weren't exposed immediately.

I've made this a warning with 6ccc978bb8066996c0aa074775def810a7ef07d3 however, as PVA picks a random TCP port number more often than CA, I think you'll quickly get tired of "decode as".
