### ISSUE TITLE
Dissection fails using Wireshark 1.10.14

### ISSUE THREAD

**Issue by Nublaikhan** [mdavidsaver/cashark#8]
In ca.lua:590 st is nil.  I believe it's due to the previous line t:add():set_text.  I don't think the set_text call returns the tree item to st.  I tested with the set_text in a separate line and all looks good.

Tested with 
CentOS 7
Wireshark 1.10.14
Lua 5.1

**Comment by mdavidsaver** [comment]
I take it you mean something like c325b9635b5bd296acd72b5297f6c10f2b31e998

set_text() does return non-nil circa wireshark 2.6.8
